apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-webapp-docker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'my-webapp-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/cgiacomini/simple-webapp-docker.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - generic:
        secret: 52b6208d2d8c8b8d
      type: Generic
    - github:
        secret: d2abd32f45cf0fd0
      type: GitHub
status:
  lastVersion: 1
