kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "simple-webapp-docker"
spec:
  template: 
    metadata:
      labels:
        name: "simple-webapp-docker"
    spec:
      containers:
        - name: "simple-webapp-docker"
          image: "172.30.1.1:5000/my-webapp/my-webapp-docker:latest"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1 
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - simple-webapp-docker
        from:
          kind: ImageStreamTag
          name: 'my-webapp-docker:latest'
          namespace: my-webapp
      type: ImageChange
    - type: ConfigChange
  strategy: 
    type: "Rolling"
